version: "2"
services:
  # Backend
  server:
    container_name: server
    build: ./
    dockerfile: ./dev/Dockerfile
    command: yarn dev
    ports:
      - 3400:3400
    volumes:
      - .:/app
    restart: unless-stopped
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5436:5436
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "bridge-applications-local"
      POSTGRES_PORT: "5436"
  migrations:
    container_name: run_migrations
    build: ./
    command: npm run db:migrate:latest
    links:
      - db
    